---
# - ros_topic_name: "/diff_drive_base_controller/cmd_vel"
#   gz_topic_name: "/diff_drive_base_controller/cmd_vel"
#   ros_type_name: "geometry_msgs/msg/Twist"
#   gz_type_name: "ignition.msgs.Twist"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/odom"
#   gz_topic_name: "/model/mbot/odometry"
#   ros_type_name: "nav_msgs/msg/Odometry"
#   gz_type_name: "gz.msgs.Odometry"
#   direction: GZ_TO_ROS
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS